### ISSUE TITLE
Runtime error while running sim.solve()

### ISSUE THREAD

**Issue by cpfpengfei** [kiranvad/pyMECSim#6]
Hi, thanks for creating this python wrapper! I tried installing via pip and also via the current git repo directly but am unable to replicate the notebook demo codes. I'm using a linux subsystem within windows to install your package. The error is as such:

![image](https://user-images.githubusercontent.com/28598792/119341066-ee729d00-bcc5-11eb-88d3-9fe6c3940a69.png)

How can this be resolved? Thanks!

**Comment by kiranvad** [comment]
Hi,
Thanks for reaching out. I need few things to better understand the issue.
Are you using one of the notebooks with in the repo? If yes, which one?
If not, can you post how you set up `exp` for the simulation?
From the error files it appears that you do not have a `float` or `int` value for one of the parameters used in `exp`

**Comment by cpfpengfei** [comment]
Hi, thanks for your reply! The notebook I was trying to replicate is: `Basic Usage.ipynb`.
After the package is installed, are there additional files I need to add to the directory?

**Comment by kiranvad** [comment]
Hi,
I just tried to run the example with my local installation and it seems to work.
There are no need to add any additional files. It should work out of the box.
Can you may be send me the `log.txt` file that should be located within the `pymecsim` folder?

**Comment by cpfpengfei** [comment]
There is no log.txt generated as well, causing FileNotFoundError when `sim.solve()` is attempted

**Comment by kiranvad** [comment]
That's surprising. If you are getting a `RuntimeError`, there should be a log.txt file.
Can you try uninstalling the pip version and use the `git clone` version and install from the folder?
For example something like the following:
```bash
git clone https://github.com/kiranvad/pyMECSim.git
cd pyMECSim
pip install -e .
```
